if NAME="Rejected" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="acceptance_rate" then do;
ROLE="TARGET";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="accepted_rejected" then do;
ROLE="INPUT";
LEVEL="BINARY";
ORDER="";
end;
if NAME="decisions_other" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
if NAME="decisions_recognized" then do;
ROLE="INPUT";
LEVEL="INTERVAL";
ORDER="";
end;
drop DROP;
