Country___territory_of_asylum_re= "Country / territory of asylum/re"n;
Label Country___territory_of_asylum_re='Country / territory of asylum/re';
drop "Country / territory of asylum/re"n;
RSD_procedure_type___level= "RSD procedure type / level"n;
Label RSD_procedure_type___level='RSD procedure type / level';
drop "RSD procedure type / level"n;
Total_decisions= "Total decisions"n;
Label Total_decisions='Total decisions';
drop "Total decisions"n;
accepted_rejected= "accepted/rejected"n;
Label accepted_rejected='accepted/rejected';
drop "accepted/rejected"n;
Encoded_procedure_type= "Encoded procedure type"n;
Label Encoded_procedure_type='Encoded procedure type';
drop "Encoded procedure type"n;
Encoded_Target_Country= "Encoded Target Country"n;
Label Encoded_Target_Country='Encoded Target Country';
drop "Encoded Target Country"n;
Encoded_Origin= "Encoded Origin"n;
Label Encoded_Origin='Encoded Origin';
drop "Encoded Origin"n;
