Country___territory_of_asylum_re= "Country / territory of asylum/re"n;
Label Country___territory_of_asylum_re='Country / territory of asylum/re';
drop "Country / territory of asylum/re"n;
RSD_procedure_type___level= "RSD procedure type / level"n;
Label RSD_procedure_type___level='RSD procedure type / level';
drop "RSD procedure type / level"n;
Tota_pending_start_year= "Tota pending start-year"n;
Label Tota_pending_start_year='Tota pending start-year';
drop "Tota pending start-year"n;
of_which_UNHCR_assisted_start_ye= "of which UNHCR-assisted(start-ye"n;
Label of_which_UNHCR_assisted_start_ye='of which UNHCR-assisted(start-ye';
drop "of which UNHCR-assisted(start-ye"n;
Applied_during_year= "Applied during year"n;
Label Applied_during_year='Applied during year';
drop "Applied during year"n;
Otherwise_closed= "Otherwise closed"n;
Label Otherwise_closed='Otherwise closed';
drop "Otherwise closed"n;
Total_decisions= "Total decisions"n;
Label Total_decisions='Total decisions';
drop "Total decisions"n;
Total_pending_end_year= "Total pending end-year"n;
Label Total_pending_end_year='Total pending end-year';
drop "Total pending end-year"n;
of_which_UNHCR_assisted_end_year= "of which UNHCR-assisted(end-year"n;
Label of_which_UNHCR_assisted_end_year='of which UNHCR-assisted(end-year';
drop "of which UNHCR-assisted(end-year"n;
accepted_rejected= "accepted/rejected"n;
Label accepted_rejected='accepted/rejected';
drop "accepted/rejected"n;
Encoded_procedure_type= "Encoded procedure type"n;
Label Encoded_procedure_type='Encoded procedure type';
drop "Encoded procedure type"n;
Encoded_Target_Country= "Encoded Target Country"n;
Label Encoded_Target_Country='Encoded Target Country';
drop "Encoded Target Country"n;
Encoded_Origin= "Encoded Origin"n;
Label Encoded_Origin='Encoded Origin';
drop "Encoded Origin"n;
